name: Workflow
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  workflow:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Use Node LTS ✨
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: yarn

    - name: Installing dependencies 📦️
      run: yarn install

    - name: Linting code 💚
      run: yarn run lint

    - name: Formatting code 💅
      run: yarn run format:check

    - name: Building 🔨
      run: yarn run build

    - name: Testing 🧪
      run: yarn test
      env:
        CI: true

    - name: Sending reporting data 📝
      run: npx codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
